from typing import Protocol
from .models import Book, User, Loan


class DbProtocol(Protocol):

    # --- COMMAND METHODS ---
    def add_book(self, book: Book): ...

    def add_user(self, user: User): ...

    def save_loan(self, loan: Loan, book_id: int): ...

    # --- QUERY METHODS ---
    def get_book_by_id(self, book_id: int) -> Book | None: ...

    def get_user_by_id(self, user_id: int) -> User | None: ...

    def get_active_loan(self, book_id: int) -> Loan | None: ...

    def remove_active_loan(self, book_id: int) -> None: ...

    # --- STATE MANAGEMENT METHODS ---
    def update_book_availability(self, book_id: int, is_available: bool) -> None: ...

    def update_loan_status(self, book_id: int) -> None: ...
